### PR TITLE
Module initialization. Added code quality tools. Added config pojo class.

### PR DESCRIPTION
**Pull request by pkornowski**

### CODE REVIEW

**Comment by pkornowski** [comment]
@dserkowski 
Looks good to me.

**Comment by dkayiwa** [comment]
@pkornowski a pull request with lost of merge commits is hard to review. Can you ensure that you have the latest upstream changes before creating one?

**Comment by pkornowski** [comment]
@dkayiwa 
Yes, we can. These merges were caused because we didn't have the repository on the OpenMRS yet.

**Comment by dkayiwa** [comment]
Oh i see! 😊

**Pull request merged**
